### ISSUE TITLE
用不了了

### ISSUE THREAD

**Issue by hujianj** [gwtak/TieBaSign#5]
File "TiebaCheckin.py", line 183, in <module>
    main()
  File "TiebaCheckin.py", line 177, in main
    client_sign(i, tbs,f["fid"],f["kw"])
NameError: name 'f' is not defined
Error: Process completed with exit code 1.

**Comment by matocool** [comment]
2024-06-04 11:24:03,127 - INFO - 获取tbs开始
2024-06-04 11:24:04,723 - INFO - 获取tbs结束
2024-06-04 11:24:04,723 - INFO - 获取关注的贴吧开始
Traceback (most recent call last):
  File "/home/runner/work/TieBaSign/TieBaSign/main.py", line 232, in <module>
    main()
  File "/home/runner/work/TieBaSign/TieBaSign/main.py", line [22](https://github.com/matocool/TieBaSign/actions/runs/9366203783/job/25783090854#step:5:23)5, in main
    client_sign(i, tbs, j["id"], j["name"])
                        ~^^^^^^
TypeError: string indices must be integers, not 'str'
Error: Process completed with exit code 1.
